//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarCollections = new HashSet<CarCollection>();
        }
    
        public int CarId { get; set; }
        public string CarName { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<CarCollection> CarCollections { get; set; }
    }
}
