//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCollection
    {
        public int CarCollectionId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
