//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCatalog
    {
        public CatCatalog()
        {
            this.CatValues = new HashSet<CatValue>();
        }
    
        public int CatalogoId { get; set; }
        public string Catalogo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<CatValue> CatValues { get; set; }
    }
}
