//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HWEntities : DbContext
    {
        public HWEntities()
            : base("name=HWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarCollection> CarCollections { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<CatCatalog> CatCatalogs { get; set; }
        public DbSet<CatValue> CatValues { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<ValidateLogin_Result> ValidateLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateLogin_Result>("ValidateLogin", usernameParameter, passwordParameter);
        }
    }
}
